/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zexus' at '4/4/17 6:13 AM' with Gradle 2.14.1
 *
 * @author zexus, @date 4/4/17 6:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
